# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file.

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [8]:
# Import pandas using the standard alias
import pandas as pd

In [14]:
# Import the file and print the first 5 rows
df = pd.read_csv('Data/Zipcode_Demos.csv')
print(df.head())

   0  Average Statistics Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0  1                 NaN          0        NaN        NaN        NaN
1  2   JURISDICTION NAME    10005.8        NaN        NaN        NaN
2  3  COUNT PARTICIPANTS        9.4        NaN        NaN        NaN
3  4        COUNT FEMALE        4.8        NaN        NaN        NaN
4  5      PERCENT FEMALE      0.404        NaN        NaN        NaN

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ... Unnamed: 37 Unnamed: 38  \
0        NaN        NaN        NaN        NaN  ...         NaN         NaN
1        NaN        NaN        NaN        NaN  ...         NaN         NaN
2        NaN        NaN        NaN        NaN  ...         NaN         NaN
3        NaN        NaN        NaN        NaN  ...         NaN         NaN
4        NaN        NaN        NaN        NaN  ...         NaN         NaN

  Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42 Unnamed: 43 Unnamed: 44  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN

  Unnamed: 45 Unnamed: 46
0         NaN         NaN
1         NaN         NaN
2         NaN         NaN
3         NaN         NaN
4         NaN         NaN

[5 rows x 47 columns]

In [10]:
# Print the last 5 rows of df
df.tail()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [11]:
# What is going on with this data set? Anything unusual?

#1. Missing values
#df.isnull().sum()

#2. Unnamed columns
df.columns

Index(['0', 'Average Statistics', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37',
       'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41',
       'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
       'Unnamed: 46'],
      dtype='object')

In [30]:
# Clean up the dataset

df = pd.read_csv('Data/Zipcode_Demos.csv', skiprows=1)

#drop empty rows and columns

df = df.dropna(axis=1, how='all')  # Drop empty columns
df = df.dropna(axis=0, how='all')  # Drop empty rows


# print(f"Number of columns after dropping NaNs: {df.shape[1]}") #to know the number of columns


if df.shape[1] >= 3:  # to make sure that DataFrame has at least 3 columns
    df = df.iloc[:, :3]  # Select the first 3

    #Rename the columns 
    df.columns = ['Index', 'Demographic', 'Value'] 
else:
    raise ValueError("The dataset has fewer than 3 columns. Please check the data format.")

#Drop rows with missing values in 'Demographic' or 'Value' columns
df = df.dropna(subset=['Demographic', 'Value'])

# Resetting the index
df = df.reset_index(drop=True)


print(f"Cleaned dataset:\n {df.head()}")

Cleaned dataset:
    Index         Demographic    Value
0      2   JURISDICTION NAME  10005.8
1      3  COUNT PARTICIPANTS      9.4
2      4        COUNT FEMALE      4.8
3      5      PERCENT FEMALE    0.404
4      6          COUNT MALE      4.6

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_Corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [32]:
# Hint: Here's a useful programming pattern to use

try:
    # Do something
    df = pd.read_csv('Yelp_Reviews_Corrupt.csv', skiprows=0, engine='python', error_incorrect_data_format=False, warn_incorrect_data_format=True)
    print("File uploaded successfully!")
    print(df.head())

except Exception as e:
    # Handle your exception error
    print(f'Error loading file: {e}')

Error loading file: read_csv() got an unexpected keyword argument 'error_incorrect_data_format'

## Summary

Congratulations, you now practiced your Pandas-importing skills.